import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'

import "./globals.css";

import AuthProvider from "./auth-provider";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({ src: './fonts/GeistVF.woff', variable: '--font-geist-sans', display: 'swap' })
const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} font-[family-name:var(--font-geist-sans)]`}
      >
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
