import type { Metadata } from "next";
import { Figtree, Inter, Poppins } from 'next/font/google'

import "./globals.css";

import AuthProvider from "./auth-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ['latin'], display: 'swap', variable: '--font-inter' })
const poppins = Poppins({ subsets: ['latin'], display: 'swap', variable: '--font-poppins', weight: ['300', '400', '500', '600' ,'700', '800']})
const figtree = Figtree({ subsets: ['latin'], variable: '--font-figtree' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${poppins.variable} font-[family-name:var(--font-figtree)]`}
      >
        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
